name: Android CI

on:
  push:
    branches: [ develop, main ]
    paths:
      - 'mobile/**'
  pull_request:
    branches: [ develop, main ]
    paths:
      - 'mobile/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Gradle
        run: cd mobile && ./gradlew build
